// <auto-generated />
using System;
using FormsDal.Contexts;
//using Infrastructure.Migrations;
//using DBTest.TempData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Model.Migrations
{
    partial class FormsSurveyDBMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Model.Entities.Form", b =>
                {
                    b.Property<string>("FormGuid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ActivityGuid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ApproveDate")
                        .HasMaxLength(14)
                        .HasColumnType("character(14)")
                        .IsFixedLength();

                    b.Property<string>("ApproveUserGuid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EntityGuid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("EntityGuidType")
                        .HasColumnType("integer");

                    b.Property<string>("FormTemplateGuid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserInCourse")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("FormGuid")
                        .HasName("Form_pkey");

                    b.HasIndex(new[] { "ActivityGuid" }, "IX_Form_ActivityGuid");

                    b.HasIndex(new[] { "ApproveUserGuid" }, "IX_Form_ApproveUserGuid");

                    b.HasIndex(new[] { "EntityGuidType" }, "IX_Form_EntityGuidType");

                    b.HasIndex(new[] { "FormTemplateGuid" }, "IX_Form_FormTemplateGuid");

                    b.HasIndex(new[] { "Status" }, "IX_Form_Status");

                    b.HasIndex(new[] { "UserInCourse" }, "IX_Form_UserInCourse");

                    b.ToTable("Form", (string)null);
                });

            modelBuilder.Entity("Model.Entities.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScoreId"));

                    b.Property<string>("ActivityGuid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("ConvertionScore")
                        .HasColumnType("double precision");

                    b.Property<string>("EntityGuid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("EntityGuidType")
                        .HasColumnType("integer");

                    b.Property<string>("FormElementGuid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FormGuid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ModelComponentComment")
                        .HasColumnType("character varying");

                    b.Property<string>("ModelComponentGuid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("OriginalScore")
                        .HasColumnType("double precision");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ScoreId");

                    b.HasIndex(new[] { "ActivityGuid" }, "IX_Score_ActivityGuid");

                    b.HasIndex(new[] { "EntityGuidType" }, "IX_Score_EntityGuidType");

                    b.HasIndex(new[] { "FormElementGuid" }, "IX_Score_FormElementGuid");

                    b.HasIndex(new[] { "FormGuid" }, "IX_Score_FormGuid");

                    b.HasIndex(new[] { "ModelComponentGuid" }, "IX_Score_ModelComponentGuid");

                    b.HasIndex(new[] { "Status" }, "IX_Score_Status");

                    b.ToTable("Score", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
