// <auto-generated />
using FormsDal.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBManageAndSurvey.Migrations.FormsDynamicDB
{
    [DbContext(typeof(FormsDynamicDBContext))]
    partial class FormsDynamicDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBManageAndSurvey.FormsDynamicDB.DynamicForm", b =>
                {
                    b.Property<int>("FormRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("ActivityGuid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CreationDate")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("EvaluatedGuid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EvaluatorGuid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FormGuid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdateDate")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("FormRecordId")
                        .HasName("Form_pkey");

                    b.ToTable("DynamicForm", (string)null);
                });

            modelBuilder.Entity("DBManageAndSurvey.FormsDynamicDB.DynamicFormComponent", b =>
                {
                    b.Property<int>("FormComponentRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<int>("FormRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("ModelComponentGuid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("FormComponentRecordId")
                        .HasName("FormComponent_pkey");

                    b.HasIndex("FormRecordId");

                    b.ToTable("DynamicFormComponent", (string)null);
                });

            modelBuilder.Entity("DBManageAndSurvey.FormsDynamicDB.DynamicFormComponent", b =>
                {
                    b.HasOne("DBManageAndSurvey.FormsDynamicDB.DynamicForm", "FormRecord")
                        .WithMany("DynamicFormComponents")
                        .HasForeignKey("FormRecordId")
                        .IsRequired()
                        .HasConstraintName("FormRecordId_FK");

                    b.Navigation("FormRecord");
                });

            modelBuilder.Entity("DBManageAndSurvey.FormsDynamicDB.DynamicForm", b =>
                {
                    b.Navigation("DynamicFormComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
